workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - test
  - build

unit_tests:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet test

build_image:
  stage: build
  image: docker:20.10.18
  services:
    - docker:20.10.18-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: bbossink/dnd-essentials-api
    IMAGE_TAG: 0.0.1-alpha
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - sudo systemctl status docker
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG